
INSERT INTO limao.Msgs
(Sender, Receiver, PhoneType, IsLocked, MsgType, MsgTime, MsgContent)
VALUES
(1,2,0,0, GETDATE(), 'While questing the noble wood of gray medieval pine, ');

INSERT INTO limao.Msgs
(Sender, Receiver, PhoneType, IsLocked, MsgType, MsgTime, MsgContent)
VALUES
(1,3,0,0, GETDATE(), 'I came upon a tomb');

INSERT INTO limao.Msgs
(Sender, Receiver, PhoneType, IsLocked, MsgType, MsgTime, MsgContent)
VALUES
(1,4,1,0, GETDATE(), 'rain sclicked, rubbed cool, ethereal');

INSERT INTO limao.Msgs
(Sender, Receiver, PhoneType, IsLocked, MsgType, MsgTime, MsgContent)
VALUES
(2,3,0,0, GETDATE(), 'Inscription vanished');

INSERT INTO limao.Msgs
(Sender, Receiver, PhoneType, IsLocked, MsgType, MsgTime, MsgContent)
VALUES
(2,4,1,0, GETDATE(), 'Melancholic Fissures');

INSERT INTO limao.Msgs
(Sender, Receiver, PhoneType, IsLocked, MsgType, MsgTime, MsgContent)
VALUES
(3,4,0,0, GETDATE(), 'What in a name? That which we call rose by another name would smell as sweet.');
