USE joe_lai_LiMao

INSERT INTO Msgs
(msg_sender, msg_receiver, msg_time, msg_content)
VALUES
(1,2,GETDATE(), 'While questing the noble wood of gray medieval pine, ');

INSERT INTO Msgs
(msg_sender, msg_receiver, msg_time, msg_content)
VALUES
(1,3,GETDATE(), 'I came upon a tomb');

INSERT INTO Msgs
(msg_sender, msg_receiver, msg_time, msg_content)
VALUES
(1,4,GETDATE(), 'rain sclicked, rubbed cool, ethereal');

INSERT INTO Msgs
(msg_sender, msg_receiver, msg_time, msg_content)
VALUES
(2,3,GETDATE(), 'Inscription vanished');

INSERT INTO Msgs
(msg_sender, msg_receiver, msg_time, msg_content)
VALUES
(2,4,GETDATE(), 'Melancholic Fissures');

INSERT INTO Msgs
(msg_sender, msg_receiver, msg_time, msg_content)
VALUES
(3,4,GETDATE(), 'What in a name? That which we call rose by another name would smell as sweet.');